/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminRole;

//Import Organization
import Business.Organization.Organization;

//Import type of organization
import Business.Organization.Organization.Type;

//Import organization directory
import Business.Organization.OrganizationDirectory;

//import card layout
import java.awt.CardLayout;

//Import JPanel
import javax.swing.JPanel;

//Import DefaultTableModel
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raj
 */


public class OrganizationManagementJPanel extends javax.swing.JPanel 


{

    private OrganizationDirectory organizationDirectory;
    
    private JPanel container;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public OrganizationManagementJPanel(JPanel container,OrganizationDirectory organizationDirectory) 
    {
        //Initialize components
        initComponents();
        
        this.
                organizationDirectory = organizationDirectory;
        
        this.
                container = container;

        //function to populate table
        populateTable();
        
        //function to populate combo box
        populateCombo();
    }
    
    //function to populate table
    private void populateTable()
    {
        
        //default tablem model created
        DefaultTableModel tableModel = (DefaultTableModel) tblOrganization.
                getModel();
        
        //set row count of table model to 0
        tableModel.
                setRowCount(0);
        
        //for loop to iterate through organization list
        for (Organization organization : organizationDirectory.
                getListOfOrganization())
            
        {
            
            Object[] row = new Object[2];
            
            row[0] = organization.
                    getOrganizationID();
            
            row[1] = organization.
                    getName();
            
            //add row to table model after each iteration
            tableModel.addRow(row);
        }
    }
    
    //Function to populate combo box
    private void populateCombo()
    {
        //Remove items from combobox
        cmbOrganization.
                removeAllItems();
        
        //iterate through types of organization
        for (Type type : Organization.
                Type.
                values())
            
        {
            if (!type.getValue().
                    equals(Type.
                            Admin.
                            getValue()))
                
                //add organization type to combo box
                cmbOrganization.addItem(type);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        lblAddOrg = new javax.swing.JButton();
        cmbOrganization = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        lblOrganizationType = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrganization.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganization);
        if (tblOrganization.getColumnModel().getColumnCount() > 0) {
            tblOrganization.getColumnModel().getColumn(0).setResizable(false);
            tblOrganization.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 770, 280));

        lblAddOrg.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblAddOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_add-organization (1).png"))); // NOI18N
        lblAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAddOrgActionPerformed(evt);
            }
        });
        add(lblAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 210, 40));

        cmbOrganization.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });
        add(cmbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 200, 40));

        btnBack.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 800, 60, 40));

        lblOrganizationType.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblOrganizationType.setText("Organization Type ");
        add(lblOrganizationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 150, 40));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAddOrgActionPerformed

        //organization type object for pointing to selected item in combo box
        Type organizationType = (Type) cmbOrganization.
                getSelectedItem();
        
        //create a new organization type in directory
        organizationDirectory.
                createOrganization(organizationType);
        
        //refresh table
        populateTable();
    }//GEN-LAST:event_lblAddOrgActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //remove container
        container.remove(this);
        
        //CardLayout object is created
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //previous cardlayout is loaded
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrganizationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lblAddOrg;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JTable tblOrganization;
    // End of variables declaration//GEN-END:variables
}
