/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LabRole;

//Import String validation
import Business.Validation.StringValidation;

//Import LabWorkRequest
import Business.WorkQueue.LabWorkReq;

//Import CardLayout
import java.awt.CardLayout;

//Import component
import java.awt.Component;

//Import InputVerifier
import javax.swing.InputVerifier;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;

/**
 *
 * @author pradyumnareddy
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel 


{

    JPanel container;
    LabWorkReq labWorkRequest;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel container, 
            LabWorkReq labWorkRequest) 
            
    {
        //Initialize components
        initComponents();
        
        //
        this.
                container = container;
        this.
                labWorkRequest = labWorkRequest;
        
        //input verifier function
        inputVerifier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(null);

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Submit Results");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(580, 370, 140, 40);

        lblResult.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblResult.setText("Lab Test Result:");
        add(lblResult);
        lblResult.setBounds(450, 220, 170, 60);

        txtResult.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });
        add(txtResult);
        txtResult.setBounds(640, 220, 240, 50);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(60, 810, 60, 30);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage);
        lblImage.setBounds(0, 0, 1378, 910);
    }// </editor-fold>//GEN-END:initComponents

    public void inputVerifier()
    {
        //Input verifier object to validate string
        InputVerifier stringVal = new StringValidation();
        
        //set input verifierv to text field
        txtResult.
                setInputVerifier(stringVal);
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //remove container
        container.
                remove(this);
        
        //Component array to fetch collection of container components
        Component[] compArray = container.getComponents();
        
        //component object to refer to components
        Component comp = compArray[compArray.length - 1];
        
        //New JPanel
        LabAssistantWorkAreaJPanel labAssistantWorkAreaPanel = (LabAssistantWorkAreaJPanel) comp;
        
        //populate table in panel
        labAssistantWorkAreaPanel.
                populateTable();
        
        //cardlayout object created
        CardLayout cardLayout = (CardLayout) container.getLayout();
        
        //load previous container
        cardLayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        //set result
        labWorkRequest.
                setResult(txtResult.
                        getText());
        
        
        if( txtResult.
                getText().
                trim().
                isEmpty() )
        {
            //Prompt message
            JOptionPane.
                    showMessageDialog(null, "Please enter all the details");
            return;
        }
        
        //set status
        labWorkRequest.
                setStatus("Completed");
        
        //message
        JOptionPane.
                showMessageDialog(null, "Lab Result Send To Doctor","Success", JOptionPane.
                        PLAIN_MESSAGE);
        txtResult.
                setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
