/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

//Import DB4OUtil
import Business.DB4OUtil.DB4OUtil;

//Import EcoSystem
import Business.EcoSystem;


//Import Organization
import Business.Organization.Organization;

//Import UserAccount
import Business.UserAccount.UserAccount;


//Import Enterprise
import Business.Enterprise.Enterprise;

//Import Network
import Business.Network.Network;


//Import JPanel
import javax.swing.JPanel;

//Import RegistrationWorkAreaJPanel
import ui.RegRole.RegistrationWorkAreaJPanel;

//Import CardLayout
import java.awt.CardLayout;

//Import Color
import java.awt.Color;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import Dimension
import java.awt.Dimension;

//Import Toolkit
import java.awt.Toolkit;
/**
 *
 * @author raj
 */
public class MainJFrame extends javax.swing.JFrame 

{

    /**
     * Creates new form MainJFrame
     */
    
    
    //EcoSystem object
    private EcoSystem ecoSystem;
    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    //Constructor
    public MainJFrame() 
    {
        //Initialize components
        initComponents();
        
        //retrieve db4OUtil system
        ecoSystem = dB4OUtil.retrieveSystem();
        
        //set size of MainJFrame
        this.setSize(1680, 1050);
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
   
        //Set panel,container background
        jPanel1.setBackground(new Color(255,255,255));
        container.setBackground(new Color(153,197,85));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        lblNewUser = new javax.swing.JLabel();
        mainImg = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jPanel1.setLayout(null);

        btnLogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(30, 440, 130, 30);

        txtUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtUserName);
        txtUserName.setBounds(20, 150, 130, 30);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(20, 250, 130, 30);

        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 204));
        lblUserName.setText("User Name");
        jPanel1.add(lblUserName);
        lblUserName.setBounds(20, 120, 130, 21);

        lblPassword.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 204));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(20, 220, 130, 21);
        jPanel1.add(loginJLabel);
        loginJLabel.setBounds(163, 346, 0, 0);

        btnLogout.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(30, 480, 130, 30);

        btnRegister.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_register.png"))); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(30, 600, 130, 40);

        lblNewUser.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNewUser.setForeground(new java.awt.Color(255, 255, 204));
        lblNewUser.setText("   New Users");
        jPanel1.add(lblNewUser);
        lblNewUser.setBounds(20, 560, 147, 34);

        mainImg.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        mainImg.setForeground(new java.awt.Color(255, 255, 204));
        mainImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110547.jpg"))); // NOI18N
        mainImg.setText("sawereeeee");
        jPanel1.add(mainImg);
        mainImg.setBounds(0, 0, 200, 1080);

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splash-edit.jpeg"))); // NOI18N
        container.add(jLabel4, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Fetch Username
        String name = txtUserName.getText();
        
        // Fetch Password into character array
        char[] passwordCharArray = txtPassword.getPassword();
        
        //Password string
        String password = String.
                valueOf(passwordCharArray);
        
        //Step1: Check user directory if a user account exist
        UserAccount account=ecoSystem.
                getUserAccountDirectory().
                authenticateProfile(name, password);
        
        //Part of Organization and Enterprise variables
        Organization partOrganization=null;
        
        Enterprise partEnterprise=null;
        
        if(account==null)
        
        {
            //Step 2: Check each enterprise with networks
            for(Network ntw:ecoSystem.getNetworkList())
            
            {
                //Step 2.a: loop through a list of enterprises
                for(Enterprise enterprise:ntw.getEnterpriseDirectory().getListOfEnterprise())
                {
                    account=enterprise.getUserAccountDirectory().authenticateProfile(name , password);
                    
                    if(account==null)
                    {
                       //Step 3:check against each organization for each enterprise
                       for(Organization org:enterprise.
                               getOrganizationDirectory().
                               getListOfOrganization())
                       {
                           
                           //Useraccount object
                           account=org.
                                   getUserAccountDirectory().
                                   authenticateProfile(name , password);
                           
                           if(account!=null)
                           {
                               partEnterprise=enterprise;
                               
                               partOrganization=org;
                               
                               break;
                           }
                       }
                        
                    }
                    else
                    {
                       partEnterprise=enterprise;
                       
                       break;
                    }
                    if(partOrganization!=null)
                    {
                        break;
                    }  
                }
                if(partEnterprise!=null)
                {
                    break;
                }
            }
        }
        
        if(account==null)
        {
            //Prompt error message
            JOptionPane.
                    showMessageDialog(null, "Invalid credentials");
            
            return;
            
        }
        else
            
        {
            //Cardlayout object created
            CardLayout cardLayout=(CardLayout)container.getLayout();
            
            //layout added to container
            container.
                    add("workArea",account.getRole().
                            createWorkArea(container, account, partOrganization, partEnterprise, ecoSystem));
            //next layout is loaded
            cardLayout.
                    next(container);
        }
        
        //Login button disabled
        btnLogin.setEnabled(false);
        
        //login button enabled
        btnLogout.setEnabled(true);
        
        //username textfield enabled
        txtUserName.setEnabled(false);
        
        //password field enabled
        txtPassword.setEnabled(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        //Set login button as disabled
        btnLogout.
                setEnabled(false);
        
        //set login button as enabled
        btnLogin.
                setEnabled(true);
        
        //set username textfield as empty
        txtUserName.
                setText("");
        
        //set password field as empty
        txtPassword.
                setText("");
        
        //set username field as enabled
        txtUserName.
                setEnabled(true);
        
        //set password field as enabled
        txtPassword.
                setEnabled(true);
        
     


        //remove all container from frame
        container.
                removeAll();
        
        //New JPanel created
        JPanel panel = new JPanel();
        
        //JPanel added to container
        container.add("blank", panel);
        
        //cardlayout object created
        CardLayout cardLayout = (CardLayout) container.getLayout();
        
        //next layout added to container
        cardLayout.next(container);
        
        
        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        //username text field is set as enabled
        txtUserName.
                setEnabled(true);
        
        //password field is set as enalbed
        txtPassword.
                setEnabled(true);
        
        //Logout button is set as disabled
        btnLogout.
                setEnabled(false);
        
        
        //login button is set as enabled
        btnLogin.
                setEnabled(true);
        
        //password field set as empty
        txtPassword.
                setText("");

        //Username textfield set as empty
        txtUserName.
                setText("");
        
      

        container.
                removeAll();
        
        //New Registration work area panel created
         RegistrationWorkAreaJPanel rwaPanel = new RegistrationWorkAreaJPanel(container, ecoSystem);
         
         //Cardlayout object created
         CardLayout cardLayout = (CardLayout) container.
                 getLayout();
         
         //Container added to panel
         container.
                 add("RegisterWorkArea", rwaPanel);
         
         //next layout loaded
         cardLayout.
                 next(container);
         
         dB4OUtil.storeSystem(ecoSystem);
         
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JLabel mainImg;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
