/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DonorRole;

//Import UserAccount
import Business.UserAccount.UserAccount;

//Import WorkRequest
import Business.WorkQueue.WorkRequest;

//Import CardLayout
import java.awt.CardLayout;

//Import DateFormat
import java.text.DateFormat;

//Import SimpleDateFormat
import java.text.SimpleDateFormat;

//Import JPanel
import javax.swing.JPanel;

//Import TableModel
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pradyumnareddy
 */
public class DonationHistory extends javax.swing.JPanel 

{
    //UserAccount  object
    private UserAccount account;
    
    //JPanel object
    private JPanel container;
    
    /**
     * Creates new form ViewDonationHistory
     */
    public DonationHistory(JPanel container, 
            UserAccount account) 
    {
        //Initialize components
        initComponents();
        this.
                container = container;
        this.
                account = account;
        
        //Set donor field to donor user account name
        txtFullName.
                setText(account.
                        getEmployee().
                        getName());
        
        //Populate table
        populateTable();
    }

    public void populateTable()
    {
        
        //table Model created
        DefaultTableModel tableModel = (DefaultTableModel)tblHistory.
                getModel();
        
        //Set row count of table model to 0
        tableModel.
                setRowCount(0);
        
        //DateFormat object created
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        
        for(WorkRequest wr : account.
                getWorkQueue().
                getListOfWorkRequest())
        {
            Object[] rowData = new Object[4];
            
            rowData[0] = wr;
            
            rowData[1] = wr.
                    getSenderAccount().
                    getEmployee().
                    getName();
            
            rowData[2] = df.
                    format(wr.
                            getRequestDate());
            
            rowData[3] = wr.
                    getResolveDate() == null ? null : df.
                    format(wr.
                    getResolveDate()); 
            
            //Add row to table model after each iteration
            tableModel.
                    addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblDonationHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, 60, 40));

        lblDonationHistory.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblDonationHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonationHistory.setText("DONATION HISTORY PANEL");
        add(lblDonationHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 46, 460, 70));

        tblHistory.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Donated to", "Requested Date", "Donated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 420, 126));

        lblFullName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblFullName.setText("Full Name:");
        add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 90, 30));

        txtFullName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtFullName.setEnabled(false);
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 320, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //Remove container
        container.remove(this);
        
        //CardLayout object created
        CardLayout cardLayout = (CardLayout)container.
                getLayout();
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonationHistory;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtFullName;
    // End of variables declaration//GEN-END:variables
}
