/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DonorRole;

//Imported UserAccount
import Business.UserAccount.UserAccount;

//Imported String validation
import Business.Validation.StringValidation;

//Imported donor work request
import Business.WorkQueue.DonorWorkReq;

//Import Management work request
import Business.WorkQueue.ManagementWorkReq;

//Imported CardLayout
import java.awt.CardLayout;

//Imported Component
import java.awt.Component;

//Imported Date
import java.util.Date;

//Imported Input verifier
import javax.swing.InputVerifier;

//Imported JOptionPane
import javax.swing.JOptionPane;

//Imported JPanel
import javax.swing.JPanel;

/**
 *
 * @author pradyumnareddy
 */
public class ProcessRequestAreaJPanel extends javax.swing.JPanel 

{
    //UserAccount object 
    private UserAccount account;
    
    //JPanel object created
    private JPanel container;
    
    //DonorWorkReq object created
    private DonorWorkReq donorWorkReq;
    
    
    /**
     * Creates new form ProcessRequestAreaJPanel
     */
    public ProcessRequestAreaJPanel(JPanel container,
            DonorWorkReq donorWorkReq, 
            UserAccount account)
    {
        
        //Initialize components
        initComponents();
        
        this.
                container = container;
        
        this.
                donorWorkReq = donorWorkReq;
        
        this.
                account = account;
        
        //request items removed to result combobox
        cmbRequestResult.
                removeAllItems();
        
        //request item added to result combobox
        cmbRequestResult.
                addItem(ManagementWorkReq.
                        REQUEST_ACCEPT);
        
        //request item added to result combobox
        cmbRequestResult.
                addItem(ManagementWorkReq.
                        REQUEST_REJECT);
        inputVerifiers();
    }
    
    //Function to verify input
    private void inputVerifiers() 
    {
         //Input verifier object created for string validation
        InputVerifier strValidation = new StringValidation();
        
        //Input verifier set to textfield
        txtComments.setInputVerifier(strValidation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        cmbRequestResult = new javax.swing.JComboBox();
        lblAddComments = new javax.swing.JLabel();
        txtComments = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblRequestResult = new javax.swing.JLabel();
        lblWorkRequestTitle = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(null);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(70, 820, 60, 40);

        cmbRequestResult.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cmbRequestResult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbRequestResult);
        cmbRequestResult.setBounds(770, 170, 163, 27);

        lblAddComments.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblAddComments.setText("Add comments: ");
        add(lblAddComments);
        lblAddComments.setBounds(540, 250, 123, 21);

        txtComments.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(txtComments);
        txtComments.setBounds(770, 240, 163, 31);

        btnSubmit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_submit.png"))); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(660, 360, 130, 40);

        lblRequestResult.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblRequestResult.setText("Request Result");
        add(lblRequestResult);
        lblRequestResult.setBounds(540, 160, 130, 40);

        lblWorkRequestTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblWorkRequestTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkRequestTitle.setText("WORK REQUEST PANEL");
        add(lblWorkRequestTitle);
        lblWorkRequestTitle.setBounds(570, 60, 340, 70);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage);
        lblImage.setBounds(0, 0, 1378, 910);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //container removed
        container.remove(this);
        
        //Component array to fetch container components
        Component[] compArray = container.
                getComponents();
        
        //New Component object created to refer to array components
        Component comp = compArray[compArray.
                length - 1];
        
        //new VewPendingRequest object created
        PendingRequest viewPendingRequest = (PendingRequest) comp;
        
        //populate table
        viewPendingRequest.
                populateJTable();
        
        //Cardlayout object created 
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //previous layout loaded
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        
        if(cmbRequestResult.
                getSelectedIndex()<0 || txtComments.
                        getText().
                        trim().
                        isEmpty())
        {
            //Error prompt
            JOptionPane.
                    showMessageDialog(null, "All fields must be filled to proceed!", "warning", JOptionPane.
                            WARNING_MESSAGE);
            return;
        }
        
        //Set details of Donor work request
        donorWorkReq.
                setFeedback(txtComments.
                        getText());

        donorWorkReq.
                setResult((String)cmbRequestResult.
                        getSelectedItem());
        
        
        
        donorWorkReq.
                setStatus(ManagementWorkReq.
                        REQUEST_COMPLETED);
        
        donorWorkReq.
                setMessage(txtComments.
                        getText());
        
        donorWorkReq.
                setResolveDate(new Date());
        account.
                getWorkQueue().
                getListOfWorkRequest().
                add(donorWorkReq);
        
        //Success prompt
        JOptionPane.
                showMessageDialog(null, "Request Processing is successful", "success", JOptionPane.
                        PLAIN_MESSAGE);
        txtComments.
                setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbRequestResult;
    private javax.swing.JLabel lblAddComments;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblRequestResult;
    private javax.swing.JLabel lblWorkRequestTitle;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables
}
