/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DonorRole;

//Import String validation
import Business.Validation.StringValidation;

import Business.Validation.DateOfBirthChecker;

//Import Email checker
import Business.Validation.EmailChecker;

//Import Number checker
import Business.Validation.NumberChecker;

//Import Phone number checker
import Business.Validation.PhoneNoChecker;

//Import Employee
import Business.Employee.Employee;

//Import UserAccount
import Business.UserAccount.UserAccount;

//Import Date of Birth checker




//Import Date
import java.util.Date;

//Import InputVerifier
import javax.swing.InputVerifier;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;


//Import ParseException
import java.text.ParseException;

//Import SimpleDateFormat
import java.text.SimpleDateFormat;

//Import CardLayout
import java.awt.CardLayout;

//Import DateFormat
import java.text.DateFormat;




/**
 *
 * @author pradyumnareddy
 */
public class ViewDonorJPanel extends javax.swing.JPanel 

{

    private JPanel container;
    private UserAccount userAccount;
    private Employee employee;
    /**
     * Creates new form ViewDonorJPanel
     */
    public ViewDonorJPanel(JPanel container, UserAccount account) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        inputVerifiers();
        employee = userAccount.getEmployee();
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        txtFullName.setText(employee.getName());
        if(employee.getDateOfBirth()!=null && employee.getAddress1()!=null && employee.getCity()!=null 
                && employee.getZip()!=null && employee.getProfession()!=null &&
                employee.getEmailId()!=null && employee.getPhoneNo()!=null
                )
        {
        txtDateOfBirth.setText(dateFormat.format(employee.getDateOfBirth()));
        txtAddress.setText(employee.getAddress1());
        txtCity.setText(employee.getCity());
        txtZip.setText(employee.getZip());
        txtOccupation.setText(employee.getProfession());
        txtEmail.setText(employee.getEmailId());
        txtPhoneNo.setText(employee.getPhoneNo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCity = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        lblDonorDetails = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtOccupation = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblDateOfBirth = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblOccupation = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCity.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 194, 28));

        txtFullName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 180, -1));

        lblZip.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblZip.setText("Zipcode:");
        add(lblZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 194, 28));

        lblDonorDetails.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblDonorDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonorDetails.setText("DONOR DETAILS");
        add(lblDonorDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 76, 281, 50));

        txtCity.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 180, -1));

        txtAddress.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 180, -1));

        txtZip.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 180, -1));

        lblAddress.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblAddress.setText("Address:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 194, 28));

        txtPhoneNo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 180, -1));

        txtDateOfBirth.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfBirthActionPerformed(evt);
            }
        });
        add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 180, -1));

        lblPhoneNumber.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number:");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 194, 28));

        lblEmail.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblEmail.setText("Email:");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 194, 28));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 60, 50));

        txtOccupation.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOccupationActionPerformed(evt);
            }
        });
        add(txtOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 180, -1));

        btnSave.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_save (1).png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 680, 110, 40));

        lblDateOfBirth.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblDateOfBirth.setText("Date Of Birth:");
        add(lblDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 194, 28));

        txtEmail.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 180, -1));

        lblOccupation.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblOccupation.setText("Occupation:");
        add(lblOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 194, 28));

        lblFullName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblFullName.setText("Full Name:");
        add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 194, 28));

        btnUpdate.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_update.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 110, 40));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed

    private void txtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //Container removed
        container.
                remove(this);
        
        //cardLayout object created
        CardLayout cardLayout = (CardLayout)container.
                getLayout();
        //previous layout added
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    
    //InputVerifier
    private void inputVerifiers()
    {
        //phone number validation
        InputVerifier phoneNoValidation = new PhoneNoChecker();
        txtPhoneNo.
                setInputVerifier(phoneNoValidation);
        
        
        //date of birth validation
        InputVerifier dateOfBirthValidation = new DateOfBirthChecker();
        txtDateOfBirth.
                setInputVerifier(dateOfBirthValidation);
        
        //email validation
        InputVerifier emailVal = new EmailChecker();
        txtEmail.
                setInputVerifier(emailVal);
        
        //number validation
        InputVerifier numberValidation = new NumberChecker();
        txtZip.
                setInputVerifier(numberValidation);
        
        
        
        
        
        
        
        
        InputVerifier stringValidation = new StringValidation();
        
        //Set Input Verifier for string validation
        
        txtOccupation.
                setInputVerifier(stringValidation);
        
        txtFullName.
                setInputVerifier(stringValidation);
        txtCity.
                setInputVerifier(stringValidation);
        txtAddress.
                setInputVerifier(stringValidation);
      
        
    }
    private void txtOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOccupationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try
            {
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                
                
                Date dateOfBirthValidation  = df.
                        parse(txtDateOfBirth.
                                getText());
                
                
                employee.
                        setFirstName(txtFullName.
                                getText());
                
                employee.
                        setAddress1(txtAddress.
                                getText());
                
                employee.
                        setCity(txtCity.
                                getText());
                
                employee.
                        setZip(txtZip.
                                getText());
                
                employee.
                        setProfession(txtOccupation.
                                getText());
                
                employee.
                        setDateOfBirth(dateOfBirthValidation);
                
                employee.
                        setPhoneNo(txtPhoneNo.
                                getText());
                
                employee.
                        setEmailId(txtEmail.
                        getText());
                
                if( txtAddress.
                        getText().
                        trim().
                        isEmpty() 
                        ||
                txtCity.
                        getText().
                        trim().
                        isEmpty() ||
                        
                txtOccupation.
                        getText().
                        trim().
                        isEmpty() ||
                        
                txtEmail.
                        getText().
                        trim().
                        isEmpty() ||
                        
                txtPhoneNo.
                        getText().
                        trim().
                        
                        isEmpty() ||
                        
                txtDateOfBirth.
                        getText().
                        trim().
                        isEmpty() ||
                        
                txtZip.
                        getText().
                        trim().
                        isEmpty()
                        )
                {
                    //Prompt error message
                    JOptionPane.
                            showMessageDialog(null, "All details must be filled!");
                    return;
                }
                userAccount.
                        setEmployee(employee);
            }
            catch(NumberFormatException nfe)
            {
                //Prompt exception error
                JOptionPane.
                        showMessageDialog(this, "Enter valid details", "warning",JOptionPane.WARNING_MESSAGE);
                return;
                
            }
            catch(ParseException pe)
            {
                //Prompt exception error
                JOptionPane.
                        showMessageDialog(this, "Enter Valid Date of Birth", "warning",JOptionPane.WARNING_MESSAGE);
                 return;
            }
        
                //Prompt exception error
                JOptionPane.
                        showMessageDialog(null, "Details Updated Successfully", "success", JOptionPane.PLAIN_MESSAGE);
                
                //update button enabled
                btnUpdate.
                        setEnabled(true);
                
                //save button disabled
                btnSave.
                        setEnabled(false);
                
                //textfield enadisabledbled
                txtFullName.
                        setEnabled(false);
                
                //dob disabled
                txtDateOfBirth.
                        setEnabled(false);
                
                //address disabled
                txtAddress.
                        setEnabled(false);
                
                //city disabled
                txtCity.
                        setEnabled(false);
                
                //zip disabled
                txtZip.
                        setEnabled(false);
                
                //occupation disabled
                txtOccupation.
                        setEnabled(false);
                
                //email disabled
                txtEmail.
                        setEnabled(false);
                
                //phone number disabled
                txtPhoneNo.
                        setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        // TODO add your handling code here:
        //Text fields enabled
        txtFullName.
                setEnabled(true);
        
        txtFullName.
                setEditable(true);
        
        txtAddress.
                setEnabled(true);
        
        txtAddress.
                setEditable(true);
        
        txtDateOfBirth.
                setEnabled(true);
        
        txtDateOfBirth.
                setEditable(true);
        
        
        txtZip.
                setEditable(true);
        
        txtOccupation.
                setEnabled(true);
        
        txtOccupation.
                setEditable(true);
        
        txtPhoneNo.
                setEnabled(true);
        
        txtPhoneNo.
                setEditable(true);
        
        txtZip.
                setEnabled(true);
        
        txtCity.
                setEditable(true);
        
        txtCity.
                setEnabled(true);
        
        txtEmail.
                setEditable(true);
        
        txtEmail.
                setEnabled(true);
        
        btnSave.
                setEnabled(true);
        
        btnUpdate.
                setEnabled(false); 
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDonorDetails;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
