/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DrugStoreRole;

//Import Enterprise
import Business.Enterprise.Enterprise;

//Import UserAccount
import Business.UserAccount.UserAccount;

//Import Drug Store work request
import Business.WorkQueue.DrugStoreWorkReq;

//Import DrugStore Organization
import Business.Organization.DrugStoreOrg;

//Imoport JPanel
import javax.swing.JPanel;

//Import table model
import javax.swing.table.DefaultTableModel;

//Import Organization
import Business.Organization.Organization;



//Import work request
import Business.WorkQueue.WorkRequest;

//Import Cardlayout
import java.awt.CardLayout;



/**
 *
 * @author merwinroy
 */
public class DrugStore extends javax.swing.JPanel {

    /**
     * Creates new form DrugStore
     */
    //Enterprise object
    private Enterprise enterprise;
    
    //UserAccount object
    private UserAccount account;
    //JPanel container object
    private JPanel container;
    
    //organization object
    private DrugStoreOrg org;
    

    
    public DrugStore(JPanel container, 
            UserAccount account, 
            Organization org,
            Enterprise enterprise) 
    
    {
        //Initialize components
        initComponents();
        
        this.
                container = container;
        this.
                account = account;
        this.
                org = (DrugStoreOrg)org;
        this.
                enterprise = enterprise;
        
        //function to populate table
        populateTable();
    }
    
    public void populateTable()
    
    {
        //table model object created
        DefaultTableModel tableModel = (DefaultTableModel)tblWorkRequest.
                getModel();
        
        //set row count of table model to 0
        tableModel.
                setRowCount(0);
        
        //for loop to iterate through list of work requests
        for(WorkRequest request : org.
                getWorkQueue().
                getListOfWorkRequest()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.
                    getSenderAccount().
                    getEmployee().
                    getName();
            row[2] = request.
                    getReceiverAccount() == null ? null : request.
                            getReceiverAccount().
                            getEmployee().
                            getName();
            row[3] = request.
                    getStatus();
            
            //Add row after every iteration to table model
            tableModel.
                    addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 150, 30));

        tblWorkRequest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 80, 660, 210));

        btnAssign.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAssign.setText("Assign Request");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 150, 30));

        btnProcess.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 150, 30));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        //refresh table
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed

        //selected row from table
        int selectedRow = tblWorkRequest.
                getSelectedRow();

        if (selectedRow < 0)
        {
            return;
        }

        //WorkRequest object
        WorkRequest workRequest = (WorkRequest)tblWorkRequest.
                getValueAt(selectedRow, 0);
        
        //set receiver account
        workRequest.
                setReceiverAccount(account);
        
        //set status
        workRequest.
                setStatus("Pending");
        
        //refresh table
        populateTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed

        //selected row from table
        int selectedRow = tblWorkRequest.
                getSelectedRow();

        if (selectedRow < 0)
        {
            return;
        }

        //get drugstore work request object value from table
        DrugStoreWorkReq drugStoreWorkRequest = (DrugStoreWorkReq)tblWorkRequest.
                getValueAt(selectedRow, 0);

        //set status
        drugStoreWorkRequest.
                setStatus("Processing");

        //New JPanel object
        ProcessWorkRequestJPanel pwrJPanel = new ProcessWorkRequestJPanel(container, drugStoreWorkRequest);
        
        //add container
        container.
                add("processWorkRequestJPanel", pwrJPanel);
        
        //CardLayout object creation
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        cardLayout.
                next(container);
    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables
}
