/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DrugStoreRole;

//Import String validation
import Business.Validation.StringValidation;

//import DrugStoreWorkRequirement
import Business.WorkQueue.DrugStoreWorkReq;

//Import CardLayout
import java.awt.CardLayout;

//Import Component
import java.awt.Component;

//Import Input Verifier
import javax.swing.InputVerifier;

//Import JOptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;
/**
 *
 * @author merwinroy
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel 

{

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    JPanel container;
    DrugStoreWorkReq drugStoreWorkReq;
    
    //Constuctor
    public ProcessWorkRequestJPanel(JPanel container,
            DrugStoreWorkReq drugStoreWorkReq) 
    
    {
        //initialize components
        initComponents();
        
        this.
                container = container;
        this.
                drugStoreWorkReq = drugStoreWorkReq;
        
        //input verifier function
        inputVerifier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        lblResults = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setText("Submit Result");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 299, 140, 50));

        lblResults.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblResults.setText("Enter  Results:");
        add(lblResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 160, 70));

        txtResult.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });
        add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 310, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 820, 60, 30));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    //input verifier function
    public void inputVerifier()
    {
        //Input verifier object for string validation
        InputVerifier stringValidation = new StringValidation();
        txtResult.setInputVerifier(stringValidation);
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        drugStoreWorkReq.
                setResult(txtResult.
                        getText());
        
        
        if( txtResult.
                getText().
                trim().
                isEmpty() )
        {
            //Prompt error message
            JOptionPane.
                    showMessageDialog(null, "Please fill all the details to proceed");
            return;
        }
        //request status set to complete
        drugStoreWorkReq.
                setStatus("Completed");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //remove container
        container.
                remove(this);
        
        //component array to fetch container components
        Component[] compArray = container.
                getComponents();
        
        //Component object to refer to array components
        Component comp = compArray[compArray.
                length - 1];
        
        //New JPanel object
        DrugStore pharmacyWorkAreaPanel = (DrugStore) comp;
        
        //populate table of panel
        pharmacyWorkAreaPanel.
                populateTable();
        
        //CardLayout object created
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //previous layout loaded
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblResults;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
