/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

//Import EcoSystem
import Business.EcoSystem;

//Import Employee
import Business.Employee.Employee;

//Import Enterprise
import Business.Enterprise.Enterprise;

//Import network
import Business.Network.Network;

//Import AdminRole
import Business.Role.AdminRole;

//Impoort UserAccount
import Business.UserAccount.UserAccount;

//Import password checker
import Business.Validation.PasswordChecker;

//Import String validation
import Business.Validation.StringValidation;

//Import cardLayout
import java.awt.CardLayout;

//import component
import java.awt.Component;

//import InputVerifier
import javax.swing.InputVerifier;

//Import JOoptionPane
import javax.swing.JOptionPane;

//Import JPanel
import javax.swing.JPanel;

//Import TableModel
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author merwinroy
 */
public class EnterpriseAdminManagementJPanel extends javax.swing.JPanel

{

     //ecoSystem object
    private EcoSystem ecoSystem;
    
    
    //JPanel container
    private JPanel container;
    
   

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public EnterpriseAdminManagementJPanel(JPanel container, 
            EcoSystem ecoSystem) 
    
    {
        
        //Initialize components
        initComponents();
        
        
        
        this.
                container = container;
        this.
                ecoSystem = ecoSystem;

        //input verifier function
        inputVerifier();
        
        //populate table function
        populateTable();
        
        //populateNetworkComboBox function
        populateNetworkComboBox();
    }

    public void inputVerifier()
    {
        InputVerifier passwordValidation = new PasswordChecker();
        txtPassword.setInputVerifier(passwordValidation);
        
        InputVerifier stringValidation = new StringValidation();
        
        txtUserName.
                setInputVerifier(stringValidation);
        
        txtName.
                setInputVerifier(stringValidation);
        
    }
    
        private void populateEnterpriseComboBox(Network network)
    
    {
        //remove items from combobox
        cmbEnterprise.
                removeAllItems();
        
        //for loop to iterate through list of enterprise
        for (Enterprise ep : network.
                getEnterpriseDirectory().
                getListOfEnterprise())
        {
                cmbEnterprise.addItem(ep);
        }
        
    }
    


    private void populateNetworkComboBox()
    {
        
        cmbNetwork.
                removeAllItems();
        
        for (Network network : ecoSystem.
                getNetworkList()){
            cmbNetwork.
                    addItem(network);
        }
    }
    

    
        //function to populate table
    private void populateTable() 
    
    {
        //tableModel object created
        DefaultTableModel tableModel = (DefaultTableModel) tblEnterprise.
                getModel();

        //set row count to 0
        tableModel.setRowCount(0);
        
        //for loop to iterate through list of networks
        for (Network network : ecoSystem.
                getNetworkList()) 
        {
            for (Enterprise enterprise : network.
                    getEnterpriseDirectory().
                    getListOfEnterprise()) 
            {
                
                for (UserAccount userAccount : enterprise.
                        getUserAccountDirectory().
                        getListOfUserAccount()) 
                
                {
                    Object[] row = new Object[3];
                    
                    row[0] = enterprise.
                            getName();
                    
                    row[1] = network.
                            getName();
                    
                    row[2] = userAccount.
                            getProfileName();

                    tableModel.addRow(row);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblNetwork = new javax.swing.JLabel();
        cmbNetwork = new javax.swing.JComboBox();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblEnterprise = new javax.swing.JLabel();
        cmbEnterprise = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEnterprise.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 523, 170));

        lblNetwork.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNetwork.setText("Network");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, 40));

        cmbNetwork.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cmbNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkActionPerformed(evt);
            }
        });
        add(cmbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 136, -1));

        lblUserName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblUserName.setText("Username");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        txtUserName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 136, -1));

        lblEnterprise.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblEnterprise.setText("Enterprise");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        cmbEnterprise.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 136, -1));

        btnSubmit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_submit.png"))); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 130, 40));

        lblPassword.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, 30));

        txtName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 136, -1));

        lblName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 90, -1));

        txtPassword.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 134, -1));

        btnBack.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 820, 60, 40));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkActionPerformed

        //Network object
        Network net = (Network) cmbNetwork.
                getSelectedItem();
        //
        if (net != null)
        {
            populateEnterpriseComboBox(net);
        }
        
        
    }//GEN-LAST:event_cmbNetworkActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        Enterprise enterprise = (Enterprise) cmbEnterprise.getSelectedItem();
        
        String username = txtUserName.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String name = txtName.getText();
        if( txtUserName.getText().trim().isEmpty() ||
            txtName.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Please enter all the details");
            return;
        }
        
        Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
        
        UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
        populateTable();
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        //container removed
        container.remove(this);
        
        //component array to collect container components
        Component[] compArray = container.getComponents();
        
        //component object to refer to array
        Component component = compArray
                [compArray.length - 1];
        
        //New JPanel
        SystemAdminWorkAreaJPanel sysAdminWorkPanel = (SystemAdminWorkAreaJPanel) component;
        
        //populate tree on JPanel
        sysAdminWorkPanel.
                populateTree();
        
        //New CardLayout
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //previous container loaded
        cardLayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbEnterprise;
    private javax.swing.JComboBox cmbNetwork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
