/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

//
import Business.EcoSystem;

import java.awt.Component;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;

import Business.Network.Network;
import Business.Validation.StringValidation;
import java.awt.CardLayout;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author merwinroy
 */
public class NetworkManagementJPanel extends javax.swing.JPanel 

{
    //EcoSystem object
    private EcoSystem system;
    //JPanel object
    private JPanel container;
    
    

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public NetworkManagementJPanel(JPanel container,
            EcoSystem system) 
            
    {
        
        //Initialize components
        initComponents();

        this.
                container = container;
        this.
                system = system;
        
        populateNetworkTable();
        
        inputVerifier();
    }
        private void populateNetworkTable() 
        {
            DefaultTableModel tableModel = (DefaultTableModel) tblNetwork.
                getModel();

            tableModel.setRowCount(0);
            for (Network net : system.
                getNetworkList()) 
            {
                Object[] row = new Object[1];
            
                row[0] = net.
                    getName();
            
                tableModel.
                    addRow(row);
            }
        }

    public void inputVerifier()
    {
        InputVerifier stringVal = new StringValidation();
        
        txtName.
                setInputVerifier(stringVal);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(null);

        tblNetwork.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNetwork);
        if (tblNetwork.getColumnModel().getColumnCount() > 0) {
            tblNetwork.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(290, 100, 404, 130);

        lblName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblName.setText("Name");
        add(lblName);
        lblName.setBounds(290, 270, 70, 40);

        btnSubmit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_submit.png"))); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(420, 380, 130, 40);

        txtName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(380, 270, 130, 40);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(70, 790, 60, 40);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage);
        lblImage.setBounds(0, 0, 1378, 910);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String name = txtName.
                getText();
        
        if( txtName.
                getText().
                trim().
                isEmpty() )
        {
            JOptionPane.
                    showMessageDialog(null, "Please enter all the details");
            return;
        }

        Network network = system.
                createAndAddNetwork();
        
        network.
                setName(name);

        populateNetworkTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.
                remove(this);
        
         Component[] componentArray = container.
                 getComponents();
         
        Component component = componentArray[componentArray.
                length - 1];
        
        SystemAdminWorkAreaJPanel sysAdminWorkPanekl = (SystemAdminWorkAreaJPanel) component;
        sysAdminWorkPanekl.
                populateTree();
        
        CardLayout cardLayout = (CardLayout) container.getLayout();
        
        cardLayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblNetwork;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
