/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;

import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;

import Business.Enterprise.Enterprise;
import Business.Network.Network;

import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author merwinroy
 * 
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel 

{

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    //JPanel object
    JPanel container;
    
    //EcoSystem object
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel container,
            EcoSystem ecosystem) 
    {
        //Initialize components
        initComponents();
        
        this.
                container=container;
        
        this.
                ecosystem=ecosystem;
        
        //populate Tree
        populateTree();
    }
    
    public void populateTree()
    {
        
        DefaultTreeModel treeModel=(DefaultTreeModel)jTree.
                getModel();
        
        ArrayList<Enterprise> listOfEnterprise;
        
        ArrayList<Organization> listOfOrganization;
        
        ArrayList<Network> listOfNetwork=ecosystem.
                getNetworkList();
        
       
        Enterprise enterprise;
        Organization organization;
        Network network;
        
        
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)treeModel.
                getRoot();
        
        root.
                removeAllChildren();
        root.
                insert(networks, 0);
        
        DefaultMutableTreeNode nodeNetwork;
        DefaultMutableTreeNode nodeEnterprise;
        DefaultMutableTreeNode nodeOrganization;
        
        for(int i=0;i<listOfNetwork.
                size();i++)
        {
            network=listOfNetwork.
                    get(i);
            
            nodeNetwork=new DefaultMutableTreeNode(network.
                    getName());
            
            networks.
                    insert(nodeNetwork, i);
            
            listOfEnterprise=network.
                    getEnterpriseDirectory().
                    getListOfEnterprise();
            
            for(int j=0; j<listOfEnterprise.size();j++)
            {
                enterprise=listOfEnterprise.
                        get(j);
                nodeEnterprise=new DefaultMutableTreeNode(enterprise.
                        getName());
                nodeNetwork.
                        insert(nodeEnterprise, j);
                
                listOfOrganization=enterprise.
                        getOrganizationDirectory().
                        getListOfOrganization();
                
                for(int k=0;k<listOfOrganization.
                        size();k++)
                {
                    organization=listOfOrganization.
                            get(i);
                    nodeOrganization=new DefaultMutableTreeNode(organization.
                            getName());
                    
                    nodeEnterprise.
                            insert(nodeOrganization, k);
                }
            }
        }
        //reload model
        treeModel.
                reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        lblSelectedNode = new javax.swing.JLabel();
        lblValueSelectedNode = new javax.swing.JLabel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane.setDividerLocation(120);

        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelectedNode.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblSelectedNode.setText("Selected Node:");
        jPanel2.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        lblValueSelectedNode.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblValueSelectedNode.setText("<View_selected_node>");
        jPanel2.add(lblValueSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        btnManageNetwork.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnManageNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_manage-network.png"))); // NOI18N
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 200, 100));

        btnManageEnterprise.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnManageEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_manage-enterprise.png"))); // NOI18N
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 200, 100));

        btnManageAdmin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnManageAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_manage-admin.png"))); // NOI18N
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 200, 100));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        jPanel2.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1378, 910));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        
        //New JPanel
        NetworkManagementJPanel managePanel=new NetworkManagementJPanel(container, ecosystem);
        
        //Container addition
        container.
                add("manageNetworkJPanel",managePanel);
        
        //CardLayout object
        CardLayout cardLayout=(CardLayout)container.
                getLayout();
        //next layout
        cardLayout.
                next(container);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        
        //New JPanel
        EnterpriseManagementJPanel mePanel=new EnterpriseManagementJPanel(container, ecosystem);
        
        //container addition
        container.
                add("manageEnterpriseJPanel",mePanel);
        
        //cardLayout add
        CardLayout cardLayout=(CardLayout)container.
                getLayout();
        
        //next container
        cardLayout.
                next(container);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        
        //New JPanel object
        EnterpriseAdminManagementJPanel meaPanel=new EnterpriseAdminManagementJPanel(container, ecosystem);
        
        //adding to container
        container.add("manageEnterpriseAdminJPanel",meaPanel);
        
        //cardlayout object creation
        CardLayout cardLayout=(CardLayout)container.getLayout();
        
        //next layout
        cardLayout.next(container);
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged

        //treeNode
        DefaultMutableTreeNode treeNode= (DefaultMutableTreeNode)jTree.
                getLastSelectedPathComponent();
        
        
        if(treeNode!=null)
        {
            
            lblValueSelectedNode.setText(treeNode.toString());
        }
    }//GEN-LAST:event_jTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSelectedNode;
    private javax.swing.JLabel lblValueSelectedNode;
    // End of variables declaration//GEN-END:variables
}
