/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;
import Business.WorkQueue.DocWorkReq;
import Business.WorkQueue.DonorWorkReq;

import Business.WorkQueue.LabWorkReq;
import Business.WorkQueue.ManagementWorkReq;
import Business.WorkQueue.WorkRequest;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrg;

import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raj
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private PatientOrg org;
    
    private Enterprise enterprise;
    
    private UserAccount account;
    
    private JPanel container;

    EcoSystem business;

    public PatientWorkAreaJPanel(JPanel container, 
            UserAccount account, 
            PatientOrg org,
            
            Enterprise enterprise,
            EcoSystem ecoSystem) 
    {
        //Initialize components
        initComponents();
        this.
                container = container;
        this.
                org = org;
        this.
                enterprise = enterprise;
        this.
                account = account;
        this.
                business=business;
        
        lblValue.
                setText(enterprise.getName());
        
        populateRequestTable();
    }
    
    
    public void populateRequestTable()
    {
        //tableModel created
        DefaultTableModel tableModel = (DefaultTableModel) tblWorkRequest.getModel();
        
        //table model row count set to 0
        tableModel.setRowCount(0);
        for (WorkRequest workReq : account.
                getWorkQueue().
                
                getListOfWorkRequest())
        {
            if(!(workReq instanceof LabWorkReq)&& 
                    !(workReq instanceof ManagementWorkReq) 
                    && !(workReq instanceof DocWorkReq))
            {
            Object[] row = new Object[4];
            
            row[0] = workReq;
            
            row[1] = workReq.
                    getReceiverAccount();
            
            row[2] = workReq.
                    getStatus();
            
            String result = ((DonorWorkReq) workReq).getResult();
            row[3] = result == null ? "Waiting" : result;
            
            
            tableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnRequestDonor = new javax.swing.JButton();
        lblDonorDashboard = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblWorkRequest.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 174, 630, 130));

        btnRefresh.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 140, 30));

        lblEnterprise.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEnterprise.setText("EnterPrise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 127, 30));

        lblValue.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 158, 26));

        btnRequestDonor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRequestDonor.setText("Request Donor");
        btnRequestDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDonorActionPerformed(evt);
            }
        });
        add(btnRequestDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 30));

        lblDonorDashboard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblDonorDashboard.setText("DONOR DASHBOARD");
        add(lblDonorDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRequestDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDonorActionPerformed
        // TODO add your handling code here:
        
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        container.
                add("RequestDonorTestJPanel", new RequestDonorTestJPanel(container, account, enterprise,business));
        
        cardLayout.
                next(container);
    }//GEN-LAST:event_btnRequestDonorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRequestDonor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonorDashboard;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables
}
