/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;

import javax.swing.JPanel;

/**
 *
 * @author raj
 */
public class PatientFrontJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientFrontJPanel
     */
    
    //JPanel object
    private JPanel container;
    
    //PatientOrganization
    private PatientOrg org;
    
    //Enterprise
    private Enterprise enterprise;
    
    //Useraccount
    private UserAccount account;
    
    //business
    EcoSystem business;
    
    public PatientFrontJPanel(JPanel container, 
            UserAccount account,
            PatientOrg org, 
            Enterprise enterprise,
            EcoSystem business) 
    {
        //Initialize component
        initComponents();
        this.
                container = container;
        
        this.org = org;
        
         this.enterprise = enterprise;
         
        this.account = account;
        
        this.business=business;
        
        lblPatientNameValue.setText(account.
                getEmployee().
                getName());
        
        lblEnterpriseValue.setText(enterprise.
                getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterpriseValue = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        btnRequestDonor = new javax.swing.JButton();
        btnRequestManager = new javax.swing.JButton();
        lblPatientName = new javax.swing.JLabel();
        lblPatientNameValue = new javax.swing.JLabel();
        btnSendVitals = new javax.swing.JButton();
        btnViewVitals = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEnterpriseValue.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEnterpriseValue.setText("<value>");
        add(lblEnterpriseValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 158, 26));

        lblEnterprise.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 127, 30));

        btnRequestDonor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRequestDonor.setText("Request Donor");
        btnRequestDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDonorActionPerformed(evt);
            }
        });
        add(btnRequestDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 250, 70));

        btnRequestManager.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRequestManager.setText("Request Manager");
        btnRequestManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestManagerActionPerformed(evt);
            }
        });
        add(btnRequestManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 240, 70));

        lblPatientName.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblPatientName.setText("Patient Name :");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 30));

        lblPatientNameValue.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblPatientNameValue.setText("<value>");
        add(lblPatientNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 158, 26));

        btnSendVitals.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSendVitals.setText("Send Vital Signs to Doctor");
        btnSendVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendVitalsActionPerformed(evt);
            }
        });
        add(btnSendVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, 70));

        btnViewVitals.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnViewVitals.setText("View Vital Signs History");
        btnViewVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVitalsActionPerformed(evt);
            }
        });
        add(btnViewVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 70));

        btnUpdateProfile.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });
        add(btnUpdateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 230, 70));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDonorActionPerformed
        // TODO add your handling code here:
        
        //Cardlayout object
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //container addition
        container.
                add("ApplicantUpdateJPanel", new PatientWorkAreaJPanel(container, account, org,enterprise,business));
        
        //next layout loaded
        cardLayout.next(container);
    }//GEN-LAST:event_btnRequestDonorActionPerformed

    private void btnRequestManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestManagerActionPerformed
        // TODO add your handling code here:
        
        //New JPanel
        RequestManagerJPanel rmPanel = new RequestManagerJPanel(container, account, org,enterprise,business);
        
        //cardlayout object
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //add to container
        container.add("RequestManagerJPanel", rmPanel);
        
        //next layout
        cardLayout.next(container);
    }//GEN-LAST:event_btnRequestManagerActionPerformed

    private void btnSendVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendVitalsActionPerformed
        // TODO add your handling code here:
        
        
        //Cardlayout object
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        
        //add to container
        container.
                add("VitalSignToDoctorJPanel", new VitalSignDocJPanel(container, account, org,enterprise,business));
        
        //next layout
        cardLayout.
                next(container);
    }//GEN-LAST:event_btnSendVitalsActionPerformed

    private void btnViewVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVitalsActionPerformed
        // TODO add your handling code here:

        //New JPanel
        VitalSignApplicantHistoryJPanel vsahPanel = new VitalSignApplicantHistoryJPanel(container, account, enterprise.getUserAccountDirectory());
        
        //card layout object
        CardLayout cardLayout = (CardLayout) container.
                getLayout();
        container.
                add("VitalSignApplicantHistoryJPanel", vsahPanel);
        
        //next layout
        cardLayout
                .next(container);
    }//GEN-LAST:event_btnViewVitalsActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        // TODO add your handling code here:
        
        //New JPanel
        UpdatePatientJPanel patientUpdateJPanel = new UpdatePatientJPanel(container, account, enterprise.
                getUserAccountDirectory());
        
        //Cardlayout object
        CardLayout layout = (CardLayout) container.
                getLayout();
        
        //add container
        container.add("ApplicantUpdateJPanel", patientUpdateJPanel);
        
        //next container
        layout.next(container);
    }//GEN-LAST:event_btnUpdateProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestDonor;
    private javax.swing.JButton btnRequestManager;
    private javax.swing.JButton btnSendVitals;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewVitals;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseValue;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientNameValue;
    // End of variables declaration//GEN-END:variables
}
