/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.EcoSystem;
import Business.WorkQueue.DocWorkReq;

import Business.WorkQueue.DonorWorkReq;
import Business.WorkQueue.LabWorkReq;
import Business.WorkQueue.ManagementWorkReq;
import Business.WorkQueue.WorkRequest;

import Business.Employee.Patient;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrg;

import Business.Organization.DocOrg;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raj
 */
public class RequestManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestManagerJPanel
     */
    private JPanel container;
    private PatientOrg organization;
    
     private Patient patient;
    private DocOrg docOrg;
    
    private Enterprise enterprise;
    private UserAccount account;
    EcoSystem ecoSystem;
   
    
    public RequestManagerJPanel(JPanel container, UserAccount account, PatientOrg organization, Enterprise enterprise, EcoSystem ecoSystem) 
    {
        initComponents();
        this.
                container = container;
        this.
                organization = organization;
        this.
                enterprise = enterprise;
        this.
                account = account;
        this.
                ecoSystem=ecoSystem;
        
        populateRequestTable();
        
        lblValue.
                setText(enterprise.getName());
    }
    
    
    public void populateRequestTable()
    {
        DefaultTableModel tableModel = (DefaultTableModel) workRequestJTable.
                getModel();
        
        tableModel.
                setRowCount(0);
        
        
        for (WorkRequest workRequest : account.
                getWorkQueue().
                getListOfWorkRequest())
        {
             if(!(workRequest instanceof LabWorkReq)&& !(workRequest instanceof DonorWorkReq) && !(workRequest instanceof DocWorkReq))
            {
                Object[] row = new Object[4];
                
                row[0] = workRequest;
                row[1] = workRequest.
                        getReceiverAccount();
                row[2] = workRequest.
                        getStatus();
           
            String result = ((ManagementWorkReq) workRequest).getResult();
            row[3] = result == null ? "Waiting" : result;
            
            
            tableModel.
                    addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnRequestManager = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblManagerDashboard = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 490, 170));

        btnRefresh.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        lblEnterprise.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, 40));

        lblValue.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 158, 26));

        btnRequestManager.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRequestManager.setText("Request Manager");
        btnRequestManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestManagerActionPerformed(evt);
            }
        });
        add(btnRequestManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 799, 100, 40));

        lblManagerDashboard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblManagerDashboard.setText("MANAGER DASHBOARD");
        add(lblManagerDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        lblImage.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRequestManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestManagerActionPerformed
        // TODO add your handling code here:
         CardLayout cardLayout = (CardLayout) container.
                 getLayout();
        container.
                add("SendToManagerJPanel", new SendToManagerJPanel(container, account, enterprise,ecoSystem));
        cardLayout.
                next(container);
    }//GEN-LAST:event_btnRequestManagerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        container.
                remove(this);
        CardLayout cardLayout = (CardLayout)container.
                getLayout();
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRequestManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblManagerDashboard;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
