/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.EcoSystem;
import Business.Validation.Checker_Main;
import Business.Validation.StringValidation;
import Business.WorkQueue.DonorWorkReq;
import Business.Enterprise.Enterprise;

import Business.Organization.DonorOrg;

import Business.UserAccount.UserAccount;


import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raj
 */
public class RequestDonorTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestDonorTestJpanel
     */
     private JPanel container;
    private Enterprise enterprise;
    private UserAccount account;
    EcoSystem business;
    private DonorOrg donorOrganization;
    RequestDonorTestJPanel(JPanel container, UserAccount account, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.account = account;
        this.business=business;
        lblValue.setText(enterprise.getName());
        inputVerifier();
        populateDoctorComboBx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblDonorName = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnRequestTest = new javax.swing.JButton();
        cmbDonor = new javax.swing.JComboBox();
        lblEnterprise = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblMessage.setText("Message");
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 80, -1));

        messageJTextField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 180, -1));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 60, 40));

        lblDonorName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblDonorName.setText("Donor Name:");
        add(lblDonorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 120, 40));

        lblValue.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 158, 26));

        btnRequestTest.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRequestTest.setText("Request Test");
        btnRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTestActionPerformed(evt);
            }
        });
        add(btnRequestTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 140, 40));

        cmbDonor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cmbDonor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 180, 30));

        lblEnterprise.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEnterprise.setText("ENTERPRISE:");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 160, 30));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    public void inputVerifier()
    {
        InputVerifier strValidation = new StringValidation();
        messageJTextField.setInputVerifier(strValidation);
    }
    
     public void populateDoctorComboBx()
    {
       try
       {
        cmbDonor.removeAllItems();
        donorOrganization =  Checker_Main.getDonorOrg(business, account);
   //    System.out.println("doctorOrganization"+doctorOrganization.getName());
       if(donorOrganization!=null)
       {
        if(donorOrganization.getUserAccountDirectory().getListOfUserAccount().isEmpty())
        {
        JOptionPane.showMessageDialog(null, "No doctors exists in our records as of now!","warning", JOptionPane.WARNING_MESSAGE);
         return;    
        }
         cmbDonor.removeAllItems();
        for(UserAccount userAccount : donorOrganization.getUserAccountDirectory().getListOfUserAccount())
        {
        cmbDonor.addItem(userAccount);
        }   
       }
       }
       catch(NullPointerException npe)
       {
       JOptionPane.showMessageDialog(null, "Donor Organization exists in our records as of now!","warning", JOptionPane.WARNING_MESSAGE);
         return;       
       }        
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        container.
                remove(this);
        
        Component[] compArray = container.
                getComponents();
        
        Component comp = compArray[compArray.
                length - 1];
        PatientWorkAreaJPanel applicantWorkAreaPanel = (PatientWorkAreaJPanel) comp;
        
        applicantWorkAreaPanel.
                populateRequestTable();
        
        CardLayout cardLayout = (CardLayout)container.
                getLayout();
        
        cardLayout.
                previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTestActionPerformed

        String message = messageJTextField.
                getText();
        if( messageJTextField.
                getText().
                trim().
                isEmpty() )
        {
            //Prompt message
            JOptionPane.
                    showMessageDialog(null, "Please enter all the details");
            return;
        }
        DonorWorkReq donorWorkRequest = new DonorWorkReq();
        donorWorkRequest.
                setSenderAccount(account);
        donorWorkRequest.
                setMessage(message);
        
        
        donorWorkRequest.
                setStatus("Sent");

        UserAccount docAccount = (UserAccount) cmbDonor.
                getSelectedItem();
        
        donorOrganization =  Checker_Main.
                getDonorOrg(business, account);
        
        donorOrganization.
                getWorkQueue().
                getListOfWorkRequest().
                add(donorWorkRequest);
            docAccount.getWorkQueue().
                    getListOfWorkRequest().
                    add(donorWorkRequest);

                    
                JOptionPane.
                        showMessageDialog(null, "Request is sent to Donor","Success", JOptionPane.
                                PLAIN_MESSAGE);
        
    }//GEN-LAST:event_btnRequestTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestTest;
    private javax.swing.JComboBox cmbDonor;
    private javax.swing.JLabel lblDonorName;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField messageJTextField;
    // End of variables declaration//GEN-END:variables
}
