/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Validation.NumberChecker;
import Business.Employee.Patient;
import Business.Employee.Employee;

import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import Business.Employee.VitalSign;

import Business.WorkQueue.DocWorkReq;
import Business.WorkQueue.DonorWorkReq;
import Business.WorkQueue.LabWorkReq;
import Business.WorkQueue.ManagementWorkReq;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;

import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author raj
 */
public class VitalSignApplicantHistoryJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form VitalSignApplicantHistoryJpanel
     */
    private JPanel container;
    private UserAccount account; 
    private Employee employee;
    private UserAccountDirectory uaDirectory;
    private Patient customer;
    private DocWorkReq dtwr;
    
    public VitalSignApplicantHistoryJPanel(JPanel container, UserAccount account, UserAccountDirectory uaDirectory) {
        initComponents();
        
        this.
                container = container;
        
        this.
                account = account;
        
        employee = account.
                getEmployee();
        
        this.
                uaDirectory = uaDirectory;
        
        customer = new Patient(account.
                getEmployee());
        
        inputVerifier();
        
        //populateTable
        populateTable();
    }
    
    
    public void populateTable()
    {
        DefaultTableModel tableModel =(DefaultTableModel) tblVitalSignsHistory.getModel();
        tableModel.setRowCount(0);
        for(WorkRequest workRequest : account.
                getWorkQueue().
                getListOfWorkRequest())
        {
            if(!(workRequest instanceof LabWorkReq)
                    && !(workRequest instanceof DonorWorkReq) 
                    && !(workRequest instanceof ManagementWorkReq))
            {
        dtwr = (DocWorkReq)workRequest;
        
        
        
        for (VitalSign vitalSign : dtwr.getVitalSignList())
        {
            Object row[]= new Object[2];
            row[0]=vitalSign;
            row[1]=vitalSign.
                    getTimeStamp();
            tableModel.addRow(row);
        }
        
    }}}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtPulse = new javax.swing.JTextField();
        lblPulse = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        barChartPanel = new javax.swing.JPanel();
        lblBloodPressure = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        lblHeartRate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblVitalSigns = new javax.swing.JLabel();
        lblViewVitalSignsHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSignsHistory = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VITAL SIGNS HISTORY PANEL");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 360, -1));

        txtWeight.setEditable(false);
        txtWeight.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 80, -1));

        lblWeight.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblWeight.setText("Weight (Pounds):");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        txtPulse.setEditable(false);
        txtPulse.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add(txtPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 80, -1));

        lblPulse.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPulse.setText("Pulse:");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        txtBloodPressure.setEditable(false);
        txtBloodPressure.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 80, -1));

        javax.swing.GroupLayout barChartPanelLayout = new javax.swing.GroupLayout(barChartPanel);
        barChartPanel.setLayout(barChartPanelLayout);
        barChartPanelLayout.setHorizontalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        barChartPanelLayout.setVerticalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        add(barChartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 590, 530));

        lblBloodPressure.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblBloodPressure.setText("Blood Pressure:");
        add(lblBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        txtHeartRate.setEditable(false);
        txtHeartRate.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateActionPerformed(evt);
            }
        });
        add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 80, -1));

        lblHeartRate.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblHeartRate.setText("Heart Rate:");
        add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Double Left_100px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 60, 40));

        lblVitalSigns.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblVitalSigns.setText("Vital Signs:");
        add(lblVitalSigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 130, 30));

        lblViewVitalSignsHistory.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblViewVitalSignsHistory.setText("View Vital Sign History ");
        add(lblViewVitalSignsHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 161, 190, 30));

        tblVitalSignsHistory.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblVitalSignsHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOOD PRESSURE", "DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVitalSignsHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 330, 94));

        btnViewDetails.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 40));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-emergency_1378x910.jpeg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1378, 910));
    }// </editor-fold>//GEN-END:initComponents

    public void inputVerifier()
    {
        InputVerifier numberValidation = new NumberChecker();
        txtHeartRate.
                setInputVerifier(numberValidation);
        txtPulse.
                setInputVerifier(numberValidation);
        txtWeight.
                setInputVerifier(numberValidation);
        txtBloodPressure.
                setInputVerifier(numberValidation
        );
    }
    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void txtHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblVitalSignsHistory.getSelectedRow();

        if (selectedrow>=0)
        {
            VitalSign vitalSign=(VitalSign)tblVitalSignsHistory.getValueAt(selectedrow, 0);
            
            
            txtHeartRate.
                    setText(String.
                            valueOf(vitalSign.
                    getHeartRate()));
            
            txtBloodPressure.
                    
                    setText(String.
                            valueOf(vitalSign.
                    getBloodPressure()));
            txtPulse.
                    setText(String.
                            valueOf(vitalSign.
                    getPulse()));
            txtWeight.
                    setText(String.
                            valueOf(vitalSign.getWeight()));
        }
        else
        {
            JOptionPane.
                    showMessageDialog(null,"Please select any row");
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barChartPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblViewVitalSignsHistory;
    private javax.swing.JLabel lblVitalSigns;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTable tblVitalSignsHistory;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
